services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Libeo\LboAnonymizer\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Libeo\LboAnonymizer\Command\AnonymizeCommand:
    tags:
      -
        name: console.command
        command: 'lbo-anonymizer:anonymize'
        description: 'Anonymize data'
        schedulable: true
